[project]
name = "uv-pck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.0",
]

[dependency-groups]
developer = [
    "pytest>=8.4.1",
    "ruff>=0.12.2",
]

  